import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton
} from '@clerk/nextjs'
import './globals.css'
import { Inter } from "next/font/google";
import type { Metadata } from "next";
import { Button } from "@/components/ui/button"


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <SignedOut>
            <div className="fixed top-4 right-4 z-50">
              <SignInButton>
                <Button>
                  登录
                </Button>
              </SignInButton>
            </div>
            <div>
              {children}
            </div>
          </SignedOut>
          <SignedIn>
            <div className="fixed top-4 right-4 z-50">
              <UserButton />
            </div>
            <div>
              {children}
            </div>
          </SignedIn>
        </body>
      </html>
    </ClerkProvider>
  )
}